name: gusto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  add_to_cart_animation: ^2.0.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  clay_containers: ^0.3.4
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  persistent_bottom_nav_bar: ^6.2.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/